FROM ubuntu:22.04

# install miniconda
RUN apt-get update \
    && apt-get install -y build-essential \
    && apt-get install -y wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:$PATH

# install singlem and dependencies. Match this invocation to the documentation
RUN conda create -y -c conda-forge -c bioconda -n singlem --strict-channel-priority --override-channels singlem'='SINGLEM_VERSION

# Download some example data so we can test the installation
RUN wget https://github.com/wwood/singlem/raw/1d204f7ef1b90435a51cdadc18d37791fbff4c9b/docker/test.fna

# activate the singlem environment
RUN echo "source activate singlem" > ~/.bashrc
ENV PATH=$CONDA_DIR/envs/singlem/bin:$PATH

# Run singlem data to download database
RUN mkdir singlem_db
RUN singlem data --output-directory singlem_db

# Run pipe
RUN singlem pipe --forward test.fna --metapackage singlem_db/* --otu-table /dev/stdout

# And lyrebird
RUN lyrebird data --output-directory lyrebird_db
RUN wget https://github.com/wwood/singlem/raw/91b0bde241d5ffc845c76a590a68041c7dc2a13e/docker/lambda_phage.fna
RUN lyrebird pipe --genome-fasta-file lambda_phage.fna --metapackage lyrebird_db/* --otu-table /dev/stdout
